version: "3"

services:
  frontend:
    build:
      context: ./Restaurant-frontend
    ports:
      - "5173:5173"

  springboot-app:
    build:
      context: ./RestaurantAPI
    restart: always
    ports:
      - 8080:8080
    networks:
      - springboot-mysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://springboot-mysql:3306/restaurant
    depends_on:
      - springboot-mysql

  springboot-mysql:
    image: mysql:5.7
    restart: always
    container_name: 'springboot-mysql'
    hostname: 'springboot-mysql'
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: restaurant
    volumes:
      - springboot-mysql-data-volume:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    
volumes:
  springboot-mysql-data-volume:

networks:
  springboot-mysql-net:
    driver: bridge
  